wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692326872.372721
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 19
      - 23
      4: 3.9.17
      5: 0.15.5
      8:
      - 5
forwardtype:
  desc: null
  value: 1
map_embed_d_dim:
  desc: null
  value: 32
num_attention_heads:
  desc: null
  value: 4
num_layers:
  desc: null
  value: 4
dropout_prob:
  desc: null
  value: 0.0
max_seq_length:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 512
log_pth:
  desc: null
  value: data/likely-cosmos-4/
noise_std:
  desc: null
  value: 0.0
pos_encoding_Flag:
  desc: null
  value: true
all_zero_target:
  desc: null
  value: 0
forward_expansion:
  desc: null
  value: 4
pre_trained:
  desc: null
  value: false
high_dim_encoder:
  desc: null
  value: true
all_steps:
  desc: null
  value: true
object_num:
  desc: null
  value: -1
model_params:
  desc: null
  value: 87926
num_data:
  desc: null
  value:
  - 100000
  - 25000
